name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    issue-transfer:
        runs-on: ubuntu-latest
        steps:
            - name: Transfer Issue
              # You may pin to the exact commit or the version.
              #uses: HosniD/transfer-issue@b88e14515d235013f18bf549dce769ace3ccfe80
              uses: HosniD/transfer-issue@v0.1.6
              with:
                # repo to copy from
                #repo-source: r1
                # repo to copy to
                repo-destination: r2
                # owner of the repo to take issue from
                owner-source: tomtanner
                # owner of the repo to save issue to
                owner-destination: tomtanner
               
       
            
