name: Manual Issue Transer Action Test
on:
  issues:
    types:
      - labeled

jobs:
  test-action:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        router:
          - manual_issue_transfer_action_test:r2

    steps:
      - uses: actions/checkout@v2
      - name: Manual Action Test
        id: test_action
        uses: ./
        with:
          token: ts.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
          router: ${{ matrix.router }}
          apply_label: MANUAL ACTION TEST
          debug: false
