name: Sync repos

on:
    issues:
        types: [opened]

jobs:
    issue-transfer:
        runs-on: ubuntu-latest
        steps:
         - name: Sync repositories
             # You may pin to the exact commit or the version.
           uses: somosprte/sync-repositories@613e9ca6b97685e6f0bd731547e6eedfc6b4bd3b
       # uses: somosprte/sync-repositories@0.0.1-ALPHA
           with:
            # Repository to receive data from you repository
            distination: r2
           # Your GitHub account username
            username: tomtanner
           # Secret toeken registered in your GitHub Account
            token_secret: SECRET
               
       
            
