name: Issue transfer2

on:
    issues:
        types: [opened]

jobs:
    issue-transfer:
        runs-on: ubuntu-latest
        steps:
            - name: Transfer Issue & Create Stub
              uses: lando/transfer-issue-action@v2
              with:
                token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
                router: roger:r2